env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "html"
rules:
  "@typescript-eslint/no-explicit-any": warn
  "@typescript-eslint/no-non-null-assertion": warn
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
      caughtErrorsIgnorePattern: "^_"
  prettier/prettier:
    - warn
    - endOfLine: auto
      singleQuote: false
  max-len:
    - warn
    - code: 100
      tabWidth: 2
      comments: 80
      ignoreComments: false
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
